// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO0ZNiicplpwwzugruydiFI0SGz59HCwU',
    appId: '1:92795863141:web:4cfda6f0ad718bfc6ec68c',
    messagingSenderId: '92795863141',
    projectId: 'finance-app-7c915',
    authDomain: 'finance-app-7c915.firebaseapp.com',
    storageBucket: 'finance-app-7c915.firebasestorage.app',
    measurementId: 'G-HDKFJYRGZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCchMS332YT61U6Mjg2KjG6Wgk72wB4qnY',
    appId: '1:92795863141:android:df46b517d7e5e2cf6ec68c',
    messagingSenderId: '92795863141',
    projectId: 'finance-app-7c915',
    storageBucket: 'finance-app-7c915.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_lpfT6IGSm7rDcwVJuZueLK0SOfDwlYM',
    appId: '1:92795863141:ios:7f74e4067545ad786ec68c',
    messagingSenderId: '92795863141',
    projectId: 'finance-app-7c915',
    storageBucket: 'finance-app-7c915.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_lpfT6IGSm7rDcwVJuZueLK0SOfDwlYM',
    appId: '1:92795863141:ios:7f74e4067545ad786ec68c',
    messagingSenderId: '92795863141',
    projectId: 'finance-app-7c915',
    storageBucket: 'finance-app-7c915.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO0ZNiicplpwwzugruydiFI0SGz59HCwU',
    appId: '1:92795863141:web:bc8074c57d136bf16ec68c',
    messagingSenderId: '92795863141',
    projectId: 'finance-app-7c915',
    authDomain: 'finance-app-7c915.firebaseapp.com',
    storageBucket: 'finance-app-7c915.firebasestorage.app',
    measurementId: 'G-KBDZ0MLNC8',
  );
}
